### ISSUE TITLE
Questions about recolor

### ISSUE THREAD

**Issue by shenmuxing** [guo-yong-zhi/WordCloud-Gallery#2]
Hello, I want to use a color similar to the image itself to generate a word cloud image. I haven't found a function similar to the example of python. Is there any related API?
```
imgobj = imread("img/bg.jpg")
image_colors = wordcloud.ImageColorGenerator(np.array(imgobj))
cloudobj.recolor(color_func=image_colors)
```
你好，我想用类似于图片本身的颜色来生成词云图，没有在示例中发现类似于如上例子中的功能，请问有没有相关的函数接口？

**Comment by guo-yong-zhi** [comment]
Do you mean `recolor!`? Here's an [example](https://github.com/guo-yong-zhi/WordCloud-Gallery#recolor).

**Comment by shenmuxing** [comment]
Sorry to reply so late. Yes,  I want examples like `recolor!`. But not exactly the same I found in it……I want a word cloud map like the one below (especially the colors) 
![image](https://user-images.githubusercontent.com/70497715/177022891-dab4eeac-0529-47a7-b086-87776ed25074.png)
Like this:
![image](https://user-images.githubusercontent.com/70497715/177022943-e0461e63-6639-4033-a19b-497d6636f688.png)
However, I can't find examples in this gallory.At most it can be done like this:
![image](https://user-images.githubusercontent.com/70497715/177022978-3ca6e88a-8af8-41f6-b9a7-dd45ef23e0ab.png)

**Comment by guo-yong-zhi** [comment]
Here we go
```julia
using Random
using Downloads
using WordCloud
imgfn = Downloads.download("https://user-images.githubusercontent.com/70497715/177022891-dab4eeac-0529-47a7-b086-87776ed25074.png")
words = [randstring(rand(1:8)) for i in 1:300]
weights = randexp(length(words))
wc = wordcloud(words, weights, mask=imgfn, transparent="white") |> generate!
recolor!(wc, style=:average)
paint(wc, background=false)
```
![ring](https://user-images.githubusercontent.com/55872791/177023974-c4676442-054b-4fcb-b6e9-9f373cc1b24b.png)


The key point is `transparent="white"`. Your picture has a gray edge (try `print(background[1,1], background[10,10])`), which makes automatic transparent color detection fail. So, set it manually. BTW, here is my code to check the transparent settings. You can run it in jupyter.
```julia
using Images
using Downloads
using WordCloud
imgfn = Downloads.download("https://user-images.githubusercontent.com/70497715/177022891-dab4eeac-0529-47a7-b086-87776ed25074.png")
background, mask = loadmask(imgfn, transparent="white", return_bitmask=true)
WordCloud.showmask(background, mask)
```

**Comment by shenmuxing** [comment]
Oh, thanks! That's brilliant.
